[package]
name = "nix-bundle-darwin"
version = "0.1.0"
edition = "2021"
license = "EUPL-1.2-or-later"

[dependencies]
anyhow = "1.0.98"
apple-codesign = "0.29.0"
clap = { version = "4.5.36", features = ["derive"] }
grep = "0.3.2"
pathdiff = "0.2.3"
schnauzer = "0.3.5"
walkdir = "2.5.0"
